[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vietqr-pro"
version = "1.0.0"
authors = [
  { name="Le Nguyen Huy Hoang", email="lnhhoang2k5@gmail.com" },
]
description = "Zero-dependency, production-grade EMVCo-compliant VietQR generator for Python (NAPAS 247 standard)."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Office/Business :: Financial :: Point-Of-Sale",
]

[project.urls]
"Homepage" = "https://github.com/huyhoang2k5/vietqr-pro"
"Bug Tracker" = "https://github.com/huyhoang2k5/vietqr-pro/issues"
